/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CertKeyDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-10T22:59:44.913+08:00")
public class CertKeyDetail {
  @SerializedName("name")
  private String name = null;

  @SerializedName("certs")
  private List<String> certs = null;

  @SerializedName("certPemList")
  private List<String> certPemList = null;

  @SerializedName("key")
  private String key = null;

  @SerializedName("keySHA1")
  private String keySHA1 = null;

  public CertKeyDetail name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CertKeyDetail certs(List<String> certs) {
    this.certs = certs;
    return this;
  }

  public CertKeyDetail addCertsItem(String certsItem) {
    if (this.certs == null) {
      this.certs = new ArrayList<String>();
    }
    this.certs.add(certsItem);
    return this;
  }

   /**
   * Get certs
   * @return certs
  **/
  @ApiModelProperty(value = "")
  public List<String> getCerts() {
    return certs;
  }

  public void setCerts(List<String> certs) {
    this.certs = certs;
  }

  public CertKeyDetail certPemList(List<String> certPemList) {
    this.certPemList = certPemList;
    return this;
  }

  public CertKeyDetail addCertPemListItem(String certPemListItem) {
    if (this.certPemList == null) {
      this.certPemList = new ArrayList<String>();
    }
    this.certPemList.add(certPemListItem);
    return this;
  }

   /**
   * Get certPemList
   * @return certPemList
  **/
  @ApiModelProperty(value = "")
  public List<String> getCertPemList() {
    return certPemList;
  }

  public void setCertPemList(List<String> certPemList) {
    this.certPemList = certPemList;
  }

  public CertKeyDetail key(String key) {
    this.key = key;
    return this;
  }

   /**
   * file path of the key
   * @return key
  **/
  @ApiModelProperty(value = "file path of the key")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public CertKeyDetail keySHA1(String keySHA1) {
    this.keySHA1 = keySHA1;
    return this;
  }

   /**
   * SHA1 of the pem of the key
   * @return keySHA1
  **/
  @ApiModelProperty(value = "SHA1 of the pem of the key")
  public String getKeySHA1() {
    return keySHA1;
  }

  public void setKeySHA1(String keySHA1) {
    this.keySHA1 = keySHA1;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertKeyDetail certKeyDetail = (CertKeyDetail) o;
    return Objects.equals(this.name, certKeyDetail.name) &&
        Objects.equals(this.certs, certKeyDetail.certs) &&
        Objects.equals(this.certPemList, certKeyDetail.certPemList) &&
        Objects.equals(this.key, certKeyDetail.key) &&
        Objects.equals(this.keySHA1, certKeyDetail.keySHA1);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, certs, certPemList, key, keySHA1);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertKeyDetail {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    certs: ").append(toIndentedString(certs)).append("\n");
    sb.append("    certPemList: ").append(toIndentedString(certPemList)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    keySHA1: ").append(toIndentedString(keySHA1)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

