/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * the protocol for health check
 */
@JsonAdapter(CheckProtocol.Adapter.class)
public enum CheckProtocol {
  
  TCP("tcp"),
  
  NONE("none");

  private String value;

  CheckProtocol(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CheckProtocol fromValue(String text) {
    for (CheckProtocol b : CheckProtocol.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CheckProtocol> {
    @Override
    public void write(final JsonWriter jsonWriter, final CheckProtocol enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CheckProtocol read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CheckProtocol.fromValue(String.valueOf(value));
    }
  }
}

