/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import vproxy.client.model.EventLoopDetail;

/**
 * EventLoopGroupDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-10T22:59:44.913+08:00")
public class EventLoopGroupDetail {
  @SerializedName("name")
  private String name = null;

  @SerializedName("eventLoopList")
  private List<EventLoopDetail> eventLoopList = null;

  public EventLoopGroupDetail name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EventLoopGroupDetail eventLoopList(List<EventLoopDetail> eventLoopList) {
    this.eventLoopList = eventLoopList;
    return this;
  }

  public EventLoopGroupDetail addEventLoopListItem(EventLoopDetail eventLoopListItem) {
    if (this.eventLoopList == null) {
      this.eventLoopList = new ArrayList<EventLoopDetail>();
    }
    this.eventLoopList.add(eventLoopListItem);
    return this;
  }

   /**
   * Get eventLoopList
   * @return eventLoopList
  **/
  @ApiModelProperty(value = "")
  public List<EventLoopDetail> getEventLoopList() {
    return eventLoopList;
  }

  public void setEventLoopList(List<EventLoopDetail> eventLoopList) {
    this.eventLoopList = eventLoopList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventLoopGroupDetail eventLoopGroupDetail = (EventLoopGroupDetail) o;
    return Objects.equals(this.name, eventLoopGroupDetail.name) &&
        Objects.equals(this.eventLoopList, eventLoopGroupDetail.eventLoopList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, eventLoopList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventLoopGroupDetail {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    eventLoopList: ").append(toIndentedString(eventLoopList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

