/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Protocol
 */
@JsonAdapter(Protocol.Adapter.class)
public enum Protocol {
  
  TCP("tcp"),
  
  HTTP("http"),
  
  H2("h2"),
  
  HTTP_1_X("http/1.x"),
  
  FRAMED_INT32("framed-int32"),
  
  DUBBO("dubbo");

  private String value;

  Protocol(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Protocol fromValue(String text) {
    for (Protocol b : Protocol.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Protocol> {
    @Override
    public void write(final JsonWriter jsonWriter, final Protocol enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Protocol read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Protocol.fromValue(String.valueOf(value));
    }
  }
}

