/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * the loadbalancing method
 */
@JsonAdapter(ServerGroupMethod.Adapter.class)
public enum ServerGroupMethod {
  
  WRR("wrr"),
  
  WLC("wlc"),
  
  SOURCE("source");

  private String value;

  ServerGroupMethod(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ServerGroupMethod fromValue(String text) {
    for (ServerGroupMethod b : ServerGroupMethod.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ServerGroupMethod> {
    @Override
    public void write(final JsonWriter jsonWriter, final ServerGroupMethod enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ServerGroupMethod read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ServerGroupMethod.fromValue(String.valueOf(value));
    }
  }
}

