/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import vproxy.client.model.ServerGroupDetail;

/**
 * ServerGroupInUpstreamDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-24T17:24:37.463+08:00")
public class ServerGroupInUpstreamDetail {
  @SerializedName("name")
  private String name = null;

  @SerializedName("weight")
  private Integer weight = null;

  @SerializedName("annotations")
  private Map<String, String> annotations = null;

  @SerializedName("serverGroup")
  private ServerGroupDetail serverGroup = null;

  public ServerGroupInUpstreamDetail name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ServerGroupInUpstreamDetail weight(Integer weight) {
    this.weight = weight;
    return this;
  }

   /**
   * weight of the server-group in the upstream
   * @return weight
  **/
  @ApiModelProperty(value = "weight of the server-group in the upstream")
  public Integer getWeight() {
    return weight;
  }

  public void setWeight(Integer weight) {
    this.weight = weight;
  }

  public ServerGroupInUpstreamDetail annotations(Map<String, String> annotations) {
    this.annotations = annotations;
    return this;
  }

  public ServerGroupInUpstreamDetail putAnnotationsItem(String key, String annotationsItem) {
    if (this.annotations == null) {
      this.annotations = new HashMap<String, String>();
    }
    this.annotations.put(key, annotationsItem);
    return this;
  }

   /**
   * Get annotations
   * @return annotations
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getAnnotations() {
    return annotations;
  }

  public void setAnnotations(Map<String, String> annotations) {
    this.annotations = annotations;
  }

  public ServerGroupInUpstreamDetail serverGroup(ServerGroupDetail serverGroup) {
    this.serverGroup = serverGroup;
    return this;
  }

   /**
   * Get serverGroup
   * @return serverGroup
  **/
  @ApiModelProperty(value = "")
  public ServerGroupDetail getServerGroup() {
    return serverGroup;
  }

  public void setServerGroup(ServerGroupDetail serverGroup) {
    this.serverGroup = serverGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerGroupInUpstreamDetail serverGroupInUpstreamDetail = (ServerGroupInUpstreamDetail) o;
    return Objects.equals(this.name, serverGroupInUpstreamDetail.name) &&
        Objects.equals(this.weight, serverGroupInUpstreamDetail.weight) &&
        Objects.equals(this.annotations, serverGroupInUpstreamDetail.annotations) &&
        Objects.equals(this.serverGroup, serverGroupInUpstreamDetail.serverGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, weight, annotations, serverGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerGroupInUpstreamDetail {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    annotations: ").append(toIndentedString(annotations)).append("\n");
    sb.append("    serverGroup: ").append(toIndentedString(serverGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

