/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Socks5ServerUpdate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-11T01:36:17.205+08:00")
public class Socks5ServerUpdate {
  @SerializedName("inBufferSize")
  private Integer inBufferSize = null;

  @SerializedName("outBufferSize")
  private Integer outBufferSize = null;

  @SerializedName("securityGroup")
  private String securityGroup = null;

  @SerializedName("allowNonBackend")
  private Boolean allowNonBackend = null;

  public Socks5ServerUpdate inBufferSize(Integer inBufferSize) {
    this.inBufferSize = inBufferSize;
    return this;
  }

   /**
   * Get inBufferSize
   * @return inBufferSize
  **/
  @ApiModelProperty(value = "")
  public Integer getInBufferSize() {
    return inBufferSize;
  }

  public void setInBufferSize(Integer inBufferSize) {
    this.inBufferSize = inBufferSize;
  }

  public Socks5ServerUpdate outBufferSize(Integer outBufferSize) {
    this.outBufferSize = outBufferSize;
    return this;
  }

   /**
   * Get outBufferSize
   * @return outBufferSize
  **/
  @ApiModelProperty(value = "")
  public Integer getOutBufferSize() {
    return outBufferSize;
  }

  public void setOutBufferSize(Integer outBufferSize) {
    this.outBufferSize = outBufferSize;
  }

  public Socks5ServerUpdate securityGroup(String securityGroup) {
    this.securityGroup = securityGroup;
    return this;
  }

   /**
   * security group reference for access control
   * @return securityGroup
  **/
  @ApiModelProperty(value = "security group reference for access control")
  public String getSecurityGroup() {
    return securityGroup;
  }

  public void setSecurityGroup(String securityGroup) {
    this.securityGroup = securityGroup;
  }

  public Socks5ServerUpdate allowNonBackend(Boolean allowNonBackend) {
    this.allowNonBackend = allowNonBackend;
    return this;
  }

   /**
   * allow or disallow to proxy to non-backend endpoints
   * @return allowNonBackend
  **/
  @ApiModelProperty(value = "allow or disallow to proxy to non-backend endpoints")
  public Boolean isAllowNonBackend() {
    return allowNonBackend;
  }

  public void setAllowNonBackend(Boolean allowNonBackend) {
    this.allowNonBackend = allowNonBackend;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Socks5ServerUpdate socks5ServerUpdate = (Socks5ServerUpdate) o;
    return Objects.equals(this.inBufferSize, socks5ServerUpdate.inBufferSize) &&
        Objects.equals(this.outBufferSize, socks5ServerUpdate.outBufferSize) &&
        Objects.equals(this.securityGroup, socks5ServerUpdate.securityGroup) &&
        Objects.equals(this.allowNonBackend, socks5ServerUpdate.allowNonBackend);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inBufferSize, outBufferSize, securityGroup, allowNonBackend);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Socks5ServerUpdate {\n");
    
    sb.append("    inBufferSize: ").append(toIndentedString(inBufferSize)).append("\n");
    sb.append("    outBufferSize: ").append(toIndentedString(outBufferSize)).append("\n");
    sb.append("    securityGroup: ").append(toIndentedString(securityGroup)).append("\n");
    sb.append("    allowNonBackend: ").append(toIndentedString(allowNonBackend)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

