/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import vproxy.client.model.ServerGroupInUpstreamDetail;

/**
 * UpstreamDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-11T01:36:17.205+08:00")
public class UpstreamDetail {
  @SerializedName("name")
  private String name = null;

  @SerializedName("serverGroupList")
  private List<ServerGroupInUpstreamDetail> serverGroupList = null;

  public UpstreamDetail name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UpstreamDetail serverGroupList(List<ServerGroupInUpstreamDetail> serverGroupList) {
    this.serverGroupList = serverGroupList;
    return this;
  }

  public UpstreamDetail addServerGroupListItem(ServerGroupInUpstreamDetail serverGroupListItem) {
    if (this.serverGroupList == null) {
      this.serverGroupList = new ArrayList<ServerGroupInUpstreamDetail>();
    }
    this.serverGroupList.add(serverGroupListItem);
    return this;
  }

   /**
   * Get serverGroupList
   * @return serverGroupList
  **/
  @ApiModelProperty(value = "")
  public List<ServerGroupInUpstreamDetail> getServerGroupList() {
    return serverGroupList;
  }

  public void setServerGroupList(List<ServerGroupInUpstreamDetail> serverGroupList) {
    this.serverGroupList = serverGroupList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpstreamDetail upstreamDetail = (UpstreamDetail) o;
    return Objects.equals(this.name, upstreamDetail.name) &&
        Objects.equals(this.serverGroupList, upstreamDetail.serverGroupList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, serverGroupList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpstreamDetail {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    serverGroupList: ").append(toIndentedString(serverGroupList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

