/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import vproxy.client.ApiException;
import vproxy.client.model.DnsServer;
import vproxy.client.model.DnsServerCreate;
import vproxy.client.model.DnsServerDetail;
import vproxy.client.model.DnsServerUpdate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DnsServerApi
 */
@Ignore
public class DnsServerApiTest {

    private final DnsServerApi api = new DnsServerApi();

    
    /**
     * add dns-server
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addDnsServerTest() throws ApiException {
        DnsServerCreate body = null;
        api.addDnsServer(body);

        // TODO: test validations
    }
    
    /**
     * get detailed info of one dns-server
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void describeDnsServerTest() throws ApiException {
        String dns = null;
        DnsServerDetail response = api.describeDnsServer(dns);

        // TODO: test validations
    }
    
    /**
     * get dns-server
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDnsServerTest() throws ApiException {
        String dns = null;
        DnsServer response = api.getDnsServer(dns);

        // TODO: test validations
    }
    
    /**
     * retrieve dns-server list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDnsServerTest() throws ApiException {
        List<DnsServer> response = api.listDnsServer();

        // TODO: test validations
    }
    
    /**
     * remove dns-server
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeDnsServerTest() throws ApiException {
        String dns = null;
        api.removeDnsServer(dns);

        // TODO: test validations
    }
    
    /**
     * update dns-server
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDnsServerTest() throws ApiException {
        String dns = null;
        DnsServerUpdate body = null;
        api.updateDnsServer(dns, body);

        // TODO: test validations
    }
    
}
