/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import org.junit.Before;
import org.junit.Test;
import vproxy.client.ApiException;

import java.util.List;

import static org.junit.Assert.*;
import static vproxy.client.TestUtils.randomName;

/**
 * API tests for EventLoopGroupApi
 */
public class EventLoopGroupApiTest {

    private final EventLoopGroupApi api = new EventLoopGroupApi();
    private String name;

    @Before
    public void setUp() {
        name = randomName("elg");
    }

    private void addEventLoopGroup() throws ApiException {
        EventLoopGroupCreate req = new EventLoopGroupCreate();
        req.setName(name);
        api.addEventLoopGroup(req);
    }

    /**
     * add event-loop-group
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addEventLoopGroupTest() throws ApiException {
        int oldLen = api.listEventLoopGroup().size();

        addEventLoopGroup();

        List<EventLoopGroup> elgList = api.listEventLoopGroup();
        assertEquals(oldLen + 1, elgList.size());
        EventLoopGroup elg = api.getEventLoopGroup(name);
        assertTrue(elgList.contains(elg));
        assertEquals(name, elg.getName());
    }

    /**
     * get detailed info of one event-loop-group
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void describeEventLoopGroupTest() throws ApiException {
        addEventLoopGroup();

        EventLoopGroupDetail elg = api.describeEventLoopGroup(name);

        assertEquals(name, elg.getName());
    }

    /**
     * get event-loop-group
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventLoopGroupTest() throws ApiException {
        addEventLoopGroup();

        EventLoopGroup response = api.getEventLoopGroup(name);

        assertNotNull(response);
    }

    /**
     * retrieve event-loop-group list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listEventLoopGroupTest() throws ApiException {
        List<EventLoopGroup> response = api.listEventLoopGroup();

        assertNotNull(response);
    }

    /**
     * remove event-loop-group
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeEventLoopGroupTest() throws ApiException {
        addEventLoopGroup();

        List<EventLoopGroup> elgListBefore = api.listEventLoopGroup();
        int lenBefore = elgListBefore.size();
        EventLoopGroup elgObject = api.getEventLoopGroup(name);
        assertTrue(elgListBefore.contains(elgObject));

        api.removeEventLoopGroup(name);

        List<EventLoopGroup> elgListAfter = api.listEventLoopGroup();
        int lenAfter = elgListAfter.size();

        assertEquals(lenBefore - 1, lenAfter);
        assertFalse(elgListAfter.contains(elgObject));
    }

}
