/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import vproxy.client.ApiException;
import vproxy.client.model.EventLoop;
import vproxy.client.model.EventLoopCreate;
import vproxy.client.model.EventLoopDetail;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EventLoopApi
 */
@Ignore
public class EventLoopApiTest {

    private final EventLoopApi api = new EventLoopApi();

    
    /**
     * add event-loop into event-loop-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addEventLoopTest() throws ApiException {
        String elg = null;
        EventLoopCreate body = null;
        api.addEventLoop(elg, body);

        // TODO: test validations
    }
    
    /**
     * get detailed info of one event-loop in event-loop-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void describeEventLoopTest() throws ApiException {
        String elg = null;
        String el = null;
        EventLoopDetail response = api.describeEventLoop(elg, el);

        // TODO: test validations
    }
    
    /**
     * get event-loop in event-loop-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEventLoopTest() throws ApiException {
        String elg = null;
        String el = null;
        EventLoop response = api.getEventLoop(elg, el);

        // TODO: test validations
    }
    
    /**
     * retrieve event-loop list from event-loop-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listEventLoopTest() throws ApiException {
        String elg = null;
        List<EventLoop> response = api.listEventLoop(elg);

        // TODO: test validations
    }
    
    /**
     * remove event-loop from event-loop-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeEventLoopTest() throws ApiException {
        String elg = null;
        String el = null;
        api.removeEventLoop(elg, el);

        // TODO: test validations
    }
    
}
