/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import vproxy.client.ApiException;
import vproxy.client.model.SecurityGroup;
import vproxy.client.model.SecurityGroupCreate;
import vproxy.client.model.SecurityGroupDetail;
import vproxy.client.model.SecurityGroupUpdate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecurityGroupApi
 */
@Ignore
public class SecurityGroupApiTest {

    private final SecurityGroupApi api = new SecurityGroupApi();

    
    /**
     * add security-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addSecurityGroupTest() throws ApiException {
        SecurityGroupCreate body = null;
        api.addSecurityGroup(body);

        // TODO: test validations
    }
    
    /**
     * get detailed info of one security-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void describeSecurityGroupTest() throws ApiException {
        String secg = null;
        SecurityGroupDetail response = api.describeSecurityGroup(secg);

        // TODO: test validations
    }
    
    /**
     * get security-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSecurityGroupTest() throws ApiException {
        String secg = null;
        SecurityGroup response = api.getSecurityGroup(secg);

        // TODO: test validations
    }
    
    /**
     * retrieve security-group list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSecurityGroupTest() throws ApiException {
        List<SecurityGroup> response = api.listSecurityGroup();

        // TODO: test validations
    }
    
    /**
     * remove security-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeSecurityGroupTest() throws ApiException {
        String secg = null;
        api.removeSecurityGroup(secg);

        // TODO: test validations
    }
    
    /**
     * update security-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSecurityGroupTest() throws ApiException {
        String secg = null;
        SecurityGroupUpdate body = null;
        api.updateSecurityGroup(secg, body);

        // TODO: test validations
    }
    
}
