/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import vproxy.client.ApiException;
import vproxy.client.model.SecurityGroupRule;
import vproxy.client.model.SecurityGroupRuleCreate;
import vproxy.client.model.SecurityGroupRuleDetail;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecurityGroupRuleApi
 */
@Ignore
public class SecurityGroupRuleApiTest {

    private final SecurityGroupRuleApi api = new SecurityGroupRuleApi();

    
    /**
     * add security-group-rule into security-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addSecurityGroupRuleTest() throws ApiException {
        String secg = null;
        SecurityGroupRuleCreate body = null;
        api.addSecurityGroupRule(secg, body);

        // TODO: test validations
    }
    
    /**
     * get detailed info of one security-group-rule in security-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void describeSecurityGroupRuleTest() throws ApiException {
        String secg = null;
        String secgr = null;
        SecurityGroupRuleDetail response = api.describeSecurityGroupRule(secg, secgr);

        // TODO: test validations
    }
    
    /**
     * get security-group-rule in security-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSecurityGroupRuleTest() throws ApiException {
        String secg = null;
        String secgr = null;
        SecurityGroupRule response = api.getSecurityGroupRule(secg, secgr);

        // TODO: test validations
    }
    
    /**
     * retrieve security-group-rule list from security-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSecurityGroupRuleTest() throws ApiException {
        String secg = null;
        List<SecurityGroupRule> response = api.listSecurityGroupRule(secg);

        // TODO: test validations
    }
    
    /**
     * remove security-group-rule from security-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeSecurityGroupRuleTest() throws ApiException {
        String secg = null;
        String secgr = null;
        api.removeSecurityGroupRule(secg, secgr);

        // TODO: test validations
    }
    
}
