/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import vproxy.client.ApiException;
import vproxy.client.model.Server;
import vproxy.client.model.ServerCreate;
import vproxy.client.model.ServerDetail;
import vproxy.client.model.ServerUpdate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServerApi
 */
@Ignore
public class ServerApiTest {

    private final ServerApi api = new ServerApi();

    
    /**
     * add server into server-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addServerTest() throws ApiException {
        String sg = null;
        ServerCreate body = null;
        api.addServer(sg, body);

        // TODO: test validations
    }
    
    /**
     * get detailed info of one server in server-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void describeServerTest() throws ApiException {
        String sg = null;
        String svr = null;
        ServerDetail response = api.describeServer(sg, svr);

        // TODO: test validations
    }
    
    /**
     * get server in server-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getServerTest() throws ApiException {
        String sg = null;
        String svr = null;
        Server response = api.getServer(sg, svr);

        // TODO: test validations
    }
    
    /**
     * retrieve server list from server-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listServerTest() throws ApiException {
        String sg = null;
        List<Server> response = api.listServer(sg);

        // TODO: test validations
    }
    
    /**
     * remove server from server-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeServerTest() throws ApiException {
        String sg = null;
        String svr = null;
        api.removeServer(sg, svr);

        // TODO: test validations
    }
    
    /**
     * update server in server-group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateServerTest() throws ApiException {
        String sg = null;
        String svr = null;
        ServerUpdate body = null;
        api.updateServer(sg, svr, body);

        // TODO: test validations
    }
    
}
