/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import vproxy.client.ApiException;
import vproxy.client.model.TcpLb;
import vproxy.client.model.TcpLbCreate;
import vproxy.client.model.TcpLbDetail;
import vproxy.client.model.TcpLbUpdate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TcpLbApi
 */
@Ignore
public class TcpLbApiTest {

    private final TcpLbApi api = new TcpLbApi();

    
    /**
     * add tcp-lb
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTcpLbTest() throws ApiException {
        TcpLbCreate body = null;
        api.addTcpLb(body);

        // TODO: test validations
    }
    
    /**
     * get detailed info of one tcp-lb
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void describeTcpLbTest() throws ApiException {
        String tl = null;
        TcpLbDetail response = api.describeTcpLb(tl);

        // TODO: test validations
    }
    
    /**
     * get tcp-lb
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTcpLbTest() throws ApiException {
        String tl = null;
        TcpLb response = api.getTcpLb(tl);

        // TODO: test validations
    }
    
    /**
     * retrieve tcp-lb list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTcpLbTest() throws ApiException {
        List<TcpLb> response = api.listTcpLb();

        // TODO: test validations
    }
    
    /**
     * remove tcp-lb
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeTcpLbTest() throws ApiException {
        String tl = null;
        api.removeTcpLb(tl);

        // TODO: test validations
    }
    
    /**
     * update tcp-lb
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTcpLbTest() throws ApiException {
        String tl = null;
        TcpLbUpdate body = null;
        api.updateTcpLb(tl, body);

        // TODO: test validations
    }
    
}
