/*
 * vproxy
 * The vproxy http controller api.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package vproxy.client.model;

import vproxy.client.ApiException;
import vproxy.client.model.Upstream;
import vproxy.client.model.UpstreamCreate;
import vproxy.client.model.UpstreamDetail;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UpstreamApi
 */
@Ignore
public class UpstreamApiTest {

    private final UpstreamApi api = new UpstreamApi();

    
    /**
     * add upstream
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addUpstreamTest() throws ApiException {
        UpstreamCreate body = null;
        api.addUpstream(body);

        // TODO: test validations
    }
    
    /**
     * get detailed info of one upstream
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void describeUpstreamTest() throws ApiException {
        String ups = null;
        UpstreamDetail response = api.describeUpstream(ups);

        // TODO: test validations
    }
    
    /**
     * get upstream
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUpstreamTest() throws ApiException {
        String ups = null;
        Upstream response = api.getUpstream(ups);

        // TODO: test validations
    }
    
    /**
     * retrieve upstream list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUpstreamTest() throws ApiException {
        List<Upstream> response = api.listUpstream();

        // TODO: test validations
    }
    
    /**
     * remove upstream
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeUpstreamTest() throws ApiException {
        String ups = null;
        api.removeUpstream(ups);

        // TODO: test validations
    }
    
}
